project_name: go-dbscan-filter

builds:
  - id: go-dbscan-filter
    main: .
    binary: go_dbscan_filter
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: serg-kovalev
    name: go-dbscan-filter
  draft: false
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: 'checksums.txt'

nfpms:
  - id: default
    package_name: go-dbscan-filter
    file_name_template: '{{ .ConventionalFileName }}'
    formats:
      - deb
      - rpm
    maintainer: serg-kovalev
    description: DBSCAN geo point clustering tool
    license: MIT
    bindir: /usr/bin

